export const GET_ALL_PRODUCT = 'GET_ALL_PRODUCT';
export const GET_ALL_PRODUCT_SUCCESS = 'GET_ALL_PRODUCT_SUCCESS';

export const GET_ALL_CATEGORY = 'GET_ALL_CATEGORY';
export const GET_ALL_CATEGORY_SUCCESS = 'GET_ALL_CATEGORY_SUCCESS';

export const GET_ALL_AUTHOR = 'GET_ALL_AUTHOR';
export const GET_ALL_AUTHOR_SUCCESS = 'GET_ALL_AUTHOR_SUCCESS';

export const GET_ALL_PUBLISHER = 'GET_ALL_PUBLISHER';
export const GET_ALL_PUBLISHER_SUCCESS = 'GET_ALL_PUBLISHER_SUCCESS';

export const GET_ALL_RELEASE_COMPANY = 'GET_ALL_RELEASE_COMPANY';
export const GET_ALL_RELEASE_COMPANY_SUCCESS = 'GET_ALL_RELEASE_COMPANY_SUCCESS';

export const GET_PRODUCT_BY_ID = 'GET_PRODUCT_BY_ID';
export const GET_PRODUCT_BY_ID_SUCCESS = 'GET_PRODUCT_BY_ID_SUCCESS';