export const GET_ALL_PRODUCT = 'GET_ALL_PRODUCT';
export const GET_ALL_PRODUCT_SUCCESS = 'GET_ALL_PRODUCT_SUCCESS';

export const GET_ALL_CATEGORY = 'GET_ALL_CATEGORY';
export const GET_ALL_CATEGORY_SUCCESS = 'GET_ALL_CATEGORY_SUCCESS';

export const GET_ALL_AUTHOR = 'GET_ALL_AUTHOR';
export const GET_ALL_AUTHOR_SUCCESS = 'GET_ALL_AUTHOR_SUCCESS';

export const GET_ALL_PUBLISHER = 'GET_ALL_PUBLISHER';
export const GET_ALL_PUBLISHER_SUCCESS = 'GET_ALL_PUBLISHER_SUCCESS';

export const GET_ALL_RELEASE_COMPANY = 'GET_ALL_RELEASE_COMPANY';
export const GET_ALL_RELEASE_COMPANY_SUCCESS = 'GET_ALL_RELEASE_COMPANY_SUCCESS';

export const GET_PRODUCT_BY_ID = 'GET_PRODUCT_BY_ID';
export const GET_PRODUCT_BY_ID_SUCCESS = 'GET_PRODUCT_BY_ID_SUCCESS';

export const RESET_PRODUCT = 'RESET_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';

export const GET_CATEGORY_BY_ID = 'GET_CATEGORY_BY_ID';
export const GET_CATEGORY_BY_ID_SUCCESS = 'GET_CATEGORY_BY_ID_SUCCESS';

export const RESET_CATEGORY = 'RESET_CATEGORY';
export const DELETE_CATEGORY = 'DELETE_CATEGORY';

export const RESET_PUBLISHER = 'RESET_PUBLISHER';
export const GET_PUBLISHER_BY_ID = 'GET_PUBLISHER_BY_ID';
export const GET_PUBLISHER_BY_ID_SUCCESS = 'GET_PUBLISHER_BY_ID_SUCCESS';
export const DELETE_PUBLISHER = 'DELETE_PUBLISHER';

export const RESET_AUTHOR = 'RESET_AUTHOR';
export const GET_AUTHOR_BY_ID = 'GET_AUTHOR_BY_ID';
export const GET_AUTHOR_BY_ID_SUCCESS = 'GET_AUTHOR_BY_ID_SUCCESS';
export const DELETE_AUTHOR = 'DELETE_AUTHOR';

export const RESET_RELEASE_COMPANY = 'RESET_AUTHOR';
export const GET_RELEASE_COMPANY_BY_ID = 'GET_RELEASE_COMPANY_BY_ID';
export const GET_RELEASE_COMPANY_BY_ID_SUCCESS = 'GET_RELEASE_COMPANY_BY_ID_SUCCESS';
export const DELETE_RELEASE_COMPANY = 'DELETE_RELEASE_COMPANY';

export const PAGINATION_AUTHOR = 'PAGINATION_AUTHOR';

export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';

export const GET_ALL_USER = 'GET_ALL_USER';
export const GET_ALL_USER_SUCCESS = 'GET_ALL_USER_SUCCESS';

export const GET_USER_BY_ID = 'GET_USER_BY_ID';
export const GET_USER_BY_ID_SUCCESS = 'GET_USER_BY_ID_SUCCESS';

export const DELETE_USER = 'DELETE_USER';
export const RESET_USER = 'RESET_USER';